### ISSUE TITLE
Unable to download images from AWS S3

### ISSUE THREAD

**Issue by Deanfei** [igordanchenko/yet-another-react-lightbox#119]
### Describe the bug

Even with the CORS enabled for the aws s3 images, the download plugin is still not working with getting CORS error.
This is because aws s3 requires the request to present the `origin` header in the request.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/29864755/236804724-7e94a9a9-3c8e-4edd-9863-ba95ce5b9b16.png">

But there is no way to override the download functionality. I have checked the source code that the save file functionality just send an xhr request without any headers.

### Expected behavior

Be able to download aws s3 images when the cors is enabled with the bucket.

### How to reproduce

create an image in aws s3 bucket and enable the cors. 

### Screenshots / Logs

<img width="924" alt="image" src="https://user-images.githubusercontent.com/29864755/236805205-19a29eca-274a-4eb0-a3ac-7a905b337d47.png">

**Comment by igordanchenko** [comment]
Thank you for bringing this up. This is an interesting interoperability issue between AWS S3 and Google Chrome.

1) Chrome doesn't send the `Origin` header when the image is rendered in the lightbox
2) S3 doesn't send the `Vary: Origin` response header because there was no `Origin` request header to begin with
3) When you hit the Download button, Chrome doesn't even send the CORS request at all because it already has the previous `GET` response in its cache and there was no `Vary: Origin` header 
4) Chrome rejects CORS request even without sending it to the server :sunglasses:

Detailed explanation: https://serverfault.com/a/856948

To solve this issue in YARL context, you can provide the `downloadUrl` slide prop that is different from the image url that you render in the lightbox (for example by appending some unique query parameter to the url):

```jsx
<Lightbox
    open={open}
    close={() => setOpen(false)}
    slides={slides.map((slide) => ({ ...slide, downloadUrl: `${slide.src}?download` }))}
    plugins={[Download]}
/>
```

p.s. Also make sure that you allow both `GET` and `HEAD` methods in S3 CORS configuration

**Comment by Deanfei** [comment]
Thanks for the reply. It's very helpful. Interesting, I didn't do anything and just tested today and everything looks working now.
The request sent from fileSaver nows includes the `origin` header. Do u know what happened here? 
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/29864755/236998471-f94bccb5-c731-4f59-98d9-74a04be5765e.png">

**Comment by igordanchenko** [comment]
The reason for this is that you have disabled browser cache in the dev tools, so Chrome doesn’t get a chance to serve the image from cache. This only confirms what I described above.

**Comment by ALICIALVO** [comment]
I was encountering with the same CORS issue : "Access to fetch at 'https://bucket-chat-name.s3.region-1.amazonaws.com/010110101001-011010110101-contactus%30(2).jpg' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." This error was when i was trying to download the image from S3 the upload worked great. I tried a bunch of solutions and trying Apigateway, user, policy changes but nothing help it to work.

After long search i've found the solution in one old question someone asked about this error. It turned out that the 'access-control-allow-origin' header was nowhere to be found in the response. it happend all because of the browser caching the requests. so the solution is that you need to add the 'mode: cors' and 'cache: no-cache' options to the fetch request.

With that solution the 'origin' header got included in the request, and voilà – the CORS error was gone.
example 1:
`const response = await fetch(url, { mode: 'cors', cache: 'no-cache' });
`
example 2:
`export const downloadMedia = async (e, originalImage) => {
    e.preventDefault();

    try {
        const response = await fetch(originalImage, {
            method: 'GET',
            mode: 'cors',           // Ensures CORS is handled
            cache: 'no-cache',      // Prevents caching issues
            headers: {
                'Content-Type': 'application/octet-stream'
            }
        });

        if (!response.ok) {
            throw new Error('Failed to fetch the file');
        }

        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.style.display = "none";
        a.href = url;

        const nameSplit = originalImage.split("/");
        const duplicateName = decodeURIComponent(nameSplit.pop());

        a.download = duplicateName;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
    } catch (error) {
        console.log('Error while downloading the image', error.message);
    }
};
`
also this was my cors configuration in s3 bucket:
`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "http://localhost:5173",
            "*"
        ],
        "ExposeHeaders": [
            "ETag",
            "Content-Length",
            "Content-Type"
        ],
        "MaxAgeSeconds": 3000
    }
] `
and bucket policy: 
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::bucket-name/*"
        }
    ]
}`
but you can use what you think is better for your usecase(:
