### ISSUE TITLE
Issues testing Lightbox with Jest

### ISSUE THREAD

**Issue by JacobwBruce** [igordanchenko/yet-another-react-lightbox#148]
### Describe the bug

Trying to test a React component that uses Lightbox, getting this error
<img width="994" alt="Screenshot 2023-07-05 at 4 53 05 PM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/47186974/9bf41b47-5048-4553-8380-3775572ebb75">
<img width="994" alt="Screenshot 2023-07-05 at 4 52 48 PM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/47186974/6c0d2dcb-f8c0-41c5-ac57-af2b9e72f119">

I've tried adding this to my jest config with all sorts of different patterns thinking it might be a issue with the file path but that didn't work either
``` 
transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!yet-another-react-lightbox/)",
 ],
```

### Expected behavior

I'm not sure what exactly to put here but I guess not conflict with jest if thats whats happening?

### How to reproduce

Test a react component with jest that is importing the Lightbox

**Comment by igordanchenko** [comment]
Seems like you have an extra trailing slash in your `transformIgnorePatterns`.

**Comment by JacobwBruce** [comment]
Yea, I've tried it a few different ways, including without the trailing slash
```
  transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!yet-another-react-lightbox)",
  ],
```
But that didn't work either

**Comment by igordanchenko** [comment]
There must be an issue with your config / project setup. I'm sorry, but I'm not in position to troubleshoot project-specific issues, especially when no details are provided.

`transformIgnorePatterns` is the right approach to instruct jest to apply transformations to specific 3rd-party dependencies.

Here is the pattern I used in the past:

```js
const esModules = ["yet-another-react-lightbox"];

module.exports = {
  testEnvironment: "jsdom",
  transformIgnorePatterns: [`node_modules/(?!${esModules.join("|")})`],
};
```

And here is a minimal project setup with jest - https://codesandbox.io/p/sandbox/yet-another-react-lightbox-148-cqhjnn?file=%2Fjest.config.js%3A1%2C1 

I'm going to go ahead and close this ticket since I do not see any particular issues that need to be addressed.

**Comment by igordanchenko** [comment]
I've updated my previous answer with 2 sample projects that you can use as a reference. I hope this helps.

**Comment by JacobwBruce** [comment]
Thank you, I appreciate it!
