### ISSUE TITLE
Inidicator bubbles for carousel

### ISSUE THREAD

**Issue by razzeee** [igordanchenko/yet-another-react-lightbox#157]
### Is your feature request related to a problem? Please describe.

I'm looking for indicatior bubbles to help the users know where they are in a carousel.

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/5943908/0ce4099c-ae96-49e2-8459-31009e44599c)

For e.g. in this screenshot they are on the first page of four.

### Describe the solution you'd like

Indicators below the image. Hiding them, when there is only one image. Ideally let users of the lib choose their own indicators.

### Additional context

Trying to switch to this library coming from `react-responsive-carousel` as we have been using this for the lightbox usecase for some time now.

**Comment by igordanchenko** [comment]
Thank you for proposing this feature. I've considered implementing such plugin, but ultimately decided to postpone and leave it in the backlog due to limited utility of this feature. Navigation bubbles serve their purpose only when there is just a handful of slides in the lightbox, and do not work well in the case of dozens of slides. There is an option to implement Instagram-like bubbles, but then they do not provide any visual context on your current position in a carousel. 

With that beings said, it's quite unlikely I'll be working on this feature in the foreseeable future. However, I'll be more than happy to accept a PR if somebody will be willing to contribute a plugin for this feature.

**Comment by razzeee** [comment]
I guess I can come up with an external component controlling the lightbox from the outside. The only thing that doesn't seem to work (or I can't find an api for) is changing the current index, but with an animation?

As changing `index` only seems to be targeted at first load.

**Comment by igordanchenko** [comment]
This should help - https://yet-another-react-lightbox.com/documentation#ControllerRef

**Comment by razzeee** [comment]
> This should help - [yet-another-react-lightbox.com/documentation#ControllerRef](https://yet-another-react-lightbox.com/documentation#ControllerRef)

Yes, that seems to help. But animations seem problematic, as soon, as I go forward/backward more then 2 images (3 and above).
[Screencast from 2023-07-16 22-45-00.webm](https://github.com/igordanchenko/yet-another-react-lightbox/assets/5943908/208e8ef2-fd5e-43f9-9887-faeb0bd8006e)

Seems to forget about the current image, while it's loading what to do?

**Comment by igordanchenko** [comment]
At any given point in time the lightbox renders `2 * carousel.preload + 1` slides in DOM (the default value is `2 * 2 + 1 = 5`). So when you navigate 3 or more slides forward/backward, the current slide immediately gets evicted from DOM.

I can suggest 2 different solutions here.

1) You can increase `carousel.preload` value to cover all slides:

```jsx
carousel={{ preload: Math.max(Math.ceil((slides.length - 1) / 2), 0) }}
```

2) You can limit the number of navigation bubbles to let's 5 to match the lightbox sliding window size.

![IMG_1786](https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/eb76e35e-2649-4bcc-9504-51e05c91bfab)
