### ISSUE TITLE
Inconsistent swipe gesture

### ISSUE THREAD

**Issue by niitish** [igordanchenko/yet-another-react-lightbox#24]
### Describe the bug

Swipe gesture on phone sometimes doesn't works properly, it either swipes multiple images or no images at all.

https://user-images.githubusercontent.com/71326553/193799864-be641b53-af2e-4738-ad89-3c8839af2788.mp4

### Expected behavior

Lightbox should swipe one image per gesture.

### How to reproduce

Following is the code I used.

```JS
<Lightbox
	open={imageView.show}
	index={currentSlide}
	close={closeImageView}
	slides={updatedImages.map((i) => {
		return {
			key: i._id,
			src: i.url,
			alt: i.imageName,
		};
	})}
	plugins={[Fullscreen, Slideshow, Zoom]}
	zoom={{
		maxZoomPixelRatio: 2,
	}}
	on={{
		view: (index) => setCurrentSlide(index),
	}}
	toolbar={{
		buttons: [
			<div key={0} className="yarl__custom_toolbar">
				<button
					className="yarl__button"
					onClick={() =>
						downloadImageWithURLCheck(
							imagesRefs.current[updatedImages[currentSlide]._id],
							isAdmin,
							allowDownload
						)
					}
				>
					<img
						src="/assets/icons/download.svg"
						alt="Download"
						className="c_yarl__icon"
					/>
				</button>
				<button
					className="yarl__button"
					onClick={() => setShowSocialShareModal(true)}
				>
					<img
						src="/assets/icons/share.svg"
						alt="Share"
						className="c_yarl__icon"
					/>
				</button>
				<button
					className="yarl__button"
					onClick={toggleFavorite}
				>
					<img
						src={
							updatedImages[currentSlide].isFavorite
								? "/assets/icons/favorite-filled.svg"
								: "/assets/icons/favorite.svg"
						}
						alt="Favorite"
						className="c_yarl__icon"
					/>
				</button>
				<button
					className="yarl__button"
					onClick={handleDeleteFolderImage}
				>
					<img
						src="/assets/icons/bin.svg"
						alt="Delete"
						className="c_yarl__icon"
					/>
				</button>
			</div>,
			"close",
		],
	}}
	carousel={{
		preload: 2,
	}}
	controller={{
		focus: true,
	}}
/>
```

**Comment by igordanchenko** [comment]
@niitish, are you experiencing swipe issues with any of the examples on the [documentation](https://yet-another-react-lightbox.com) website?

Also, would you be so kind as to make another screen recording with slowed-down swipe animation?

```jsx
<Lightbox
  animation={{ swipe: 3000 }}
  ...
/>
```

**Comment by niitish** [comment]
No. Documentation website's examples are rather smooth. But when loading lightbox with slightly greater number of images, unexpected delay in swiping can be observed on some of the slides.
One more thing I noticed is that on swiping, the swipe timing of  ```animation={{ swipe: 3000 }}``` is not being followed.

Please check out this fork of the documentation website:
https://tsvez0.csb.app/examples/basic
https://user-images.githubusercontent.com/71326553/194518052-bf81c7d3-664e-4800-85cf-6505ac8178a6.mp4

**Comment by igordanchenko** [comment]
@niitish,

> But when loading lightbox with slightly greater number of images, unexpected delay in swiping can be observed on some of the slides.

The number of slides shouldn't really affect performance since at any given point in time the lightbox renders only `(2 * carousel.preload) + 1` slides.

> One more thing I noticed is that on swiping, the swipe timing of animation={{ swipe: 3000 }} is not being followed.

It is being honored. If you click the navigation button, you'll see that animation runs for 3 seconds. However when you use touch gesture, the animation duration is very likely to be shorter depending on how quickly you swipe.

> Please check out this fork of the documentation website

This demo runs pretty smoothly on my phone.

https://user-images.githubusercontent.com/64441155/194625974-1ea8e469-603a-4480-a6a7-a6c23cf057ad.mp4

However, I'd recommend you use `srcSet` and supply images of smaller resolution that are more appropriate for mobile viewports. Some mobile devices may struggle with 3rd acceleration, especially when all images are 3840x2160.

As to your original issue, the video recording from your original post did show some weird behavior, so I'm assuming it may be implementation specific. I'll be happy to take a look if you can share a complete demo reproducing the issue.

**Comment by igordanchenko** [comment]
@niitish, are you still experiencing this issue? I'll be happy to troubleshoot, but I need a reproducible demo.
