### ISSUE TITLE
Add onError callback to the video plugin

### ISSUE THREAD

**Issue by oceandrama** [igordanchenko/yet-another-react-lightbox#272]
### Is your feature request related to a problem? Please describe.

Now, if `video` slide can't play the sourse, it looks broken
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/23439079/b37ccd77-5e4f-42b7-9c8f-2a8c3db687d9)

### Describe the solution you'd like

Add the same onError callback as in `ImageSldie` https://github.com/igordanchenko/yet-another-react-lightbox/blob/3f18c23165073f65364938db42afd75722c11903/src/components/ImageSlide.tsx#L138

**Comment by igordanchenko** [comment]
The UX is browser-specific in this case, and some browsers convey the error message better than others. 

Chrome:
<img width="560" alt="Screenshot 2024-05-21 at 11 56 22 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/f68d6e5d-5b28-4221-8d07-ec34bbe1c55c">

Safari:
<img width="566" alt="Screenshot 2024-05-21 at 11 56 51 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/c9ab8f98-77f3-4e7d-8a92-c5146bdf112f">

Firefox:
<img width="571" alt="Screenshot 2024-05-21 at 11 57 11 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/3d985a9b-f7c1-4e78-8fee-391a967c3108">

IMO, the presented UX is sufficient and self-explanatory.

**Comment by oceandrama** [comment]
I don't think so. Only Firefox displays the error message. Everything else looks like it's loading. Also all browsers have UI for broken images, so why did you add onError callback for it?

**Comment by igordanchenko** [comment]
> Everything else looks like it's loading. 

Both Chrome and Safari have loading spinners, which visually differentiate the loading state. 

Chrome:
<img width="525" alt="Screenshot 2024-05-22 at 10 12 30 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/6c791ff9-27cd-4584-aaa6-b7a7fcfbf350">

Safari:
<img width="567" alt="Screenshot 2024-05-22 at 10 15 44 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/a1021d0a-3b76-45d6-9965-0f1447261a60">

While I agree that the UX could use some improvements, this is not something I'd want to address within the scope of this library. 

> Also all browsers have UI for broken images, so why did you add onError callback for it?

Because image slides have custom loading indicator, handling the error state was pretty much a requirement.
