### ISSUE TITLE
Safari displays a zoomed image in degraded quality

### ISSUE THREAD

**Issue by nazar-ch** [igordanchenko/yet-another-react-lightbox#290]
### Describe the bug

The current desktop & mobile versions of Safari initially load smaller images from the slide's `scrSet`, and after zooming in and replacing the smaller image with the larger version, render it in degraded quality.

Please check the screenshot (or the recording) with the illustration of the issue.

The browser loads the correct image (I checked this by using visually marked images), but displays it in a quality that resembles the low res version.

It seems to be caused by a bug in Safari. The `transform: translateZ(0px)` in the `img` style may change the way how the image is rendered and something in the rendering engine caches the original image dimensions. When `src` is replaced with another larger image it's rendered with the cached smaller dimensions.

Disabling `translateZ` by adding this style resolves the problem:
```
.yarl__slide_image {
    -webkit-transform: none !important;
}
```

### Expected behavior

The high res image retains its quality

### How to reproduce

* Create the lightbox using `srcSet` with variants of different sizes. 
* Open in iOS Safari or Desktop Safari with the smallest window width.
* Zoom in and see that `large.jpg` is displayed with degraded quality.

```
<Lightbox
    slides={[
        {
           // ...
           srcSet: [
                { width: 500, height: 500, src: 'small.jpg' },
                { width: 3000, height: 3000, src: 'large.jpg' },
            ],
        },
    ]}
/>;
```

### Screenshots / Logs

![safari-chrome-image-quality](https://github.com/igordanchenko/yet-another-react-lightbox/assets/8333702/1cf33dc1-d174-47ba-8852-d9e48632a33a)

Recording:
https://github.com/igordanchenko/yet-another-react-lightbox/assets/8333702/435e9aca-0f57-447e-8d85-42c83968307f

**Comment by igordanchenko** [comment]
Thank you for the very detailed report. I appreciate it!

Apparently, you discovered a Safari bug caused by the code meant to workaround a different Safari bug :sweat_smile:

https://github.com/igordanchenko/yet-another-react-lightbox/blob/39426d4d3918c1c0744a5d26de9130c7e6aa647a/src/plugins/zoom/ResponsiveImage.tsx#L85-L88

https://github.com/igordanchenko/yet-another-react-lightbox/blob/39426d4d3918c1c0744a5d26de9130c7e6aa647a/src/styles.scss#L100-L106

I'll implement another workaround to fix the blurred image, but keep in mind that images will still be blurred during zoom-in / zoom-out transition.

https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/3569df8c-f666-4749-b46c-3bd83cbd2e4d

It's another Webkit bug dating back to 2009 :scream:

https://bugs.webkit.org/show_bug.cgi?id=27684

**Comment by nazar-ch** [comment]
🤦 

Thank you for the fix! The turnaround time is extraordinary :)

The blurry part feels like expected behavior, I hope it will be fine for users.
