### ISSUE TITLE
Sliding event getting stuck "in-between" in Chrome

### ISSUE THREAD

**Issue by xAlban** [igordanchenko/yet-another-react-lightbox#59]
### Describe the bug

As explained in the Firefox issue, when I drag the slide in Chrome sometimes it get stuck and doesn't slide all the way.

### Expected behavior

It is expected to slide smoothly without getting stuck.

### How to reproduce

Go to any official demo with Google Chrome and drag a slide.

### Screenshots / Logs

ScreenRecording: https://streamable.com/eu32x9

**Comment by igordanchenko** [comment]
1) What pointer device are you using? Mac touchpad? External trackpad? Mouse?
2) Are you able to reproduce this issue with all Chrome extensions disabled?
3) Are you seeing this issue only in Chrome?
4) Are you using the latest version of Chrome?
5) Are you seeing this issue on any other device?

I'm asking all these questions because I'm still unable to reproduce this issue on my end and I need your help to get to the bottom of it.

**Comment by xAlban** [comment]
It is linked to my pointer setup ! As I'm using a server to communicate between device I guess there are some drop in the communication.

I'm closing the issue thanks again for the help !

**Comment by igordanchenko** [comment]
Hi Alban,

Thank you for providing the additional details about your environment. I investigated this issue further and was finally able to reproduce it on my Mac. It happens extremely rarely, but it does happen. 

As it turns out, the root cause is two-fold:  
1) out-of-order events in Chrome (`onpointermove` event with `buttons: 0` sometimes fires before the corresponding `onpointerup` event)
2) the fix implemented in #48

I'm wondering if you can help me test the fix in your environment. The patched version is available here: 

https://yet-another-react-lightbox-2caw0pqcb-igor-danchenko.vercel.app/examples/basic

I'd really appreciate it if you could give it a go in your environment and see if it addresses this bug.

**Comment by igordanchenko** [comment]
I'll go ahead and release this fix since I no longer see this issue in my tests. Please let me know if you have any feedback.
