### ISSUE TITLE
Dynamic Background Opacity for Lightbox

### ISSUE THREAD

**Issue by d4mr** [igordanchenko/yet-another-react-lightbox#6]
### Is your feature request related to a problem? Please describe.

Currently the background opacity for the lighbox is 100%. It would be good to have an easy way to customise that, and make other things in the background more visible.

### Describe the solution you'd like

A background Opacity prop for the Lightbox would make things easy. Alternatively, adding support for className would make it more flexible.

**Comment by igordanchenko** [comment]
You can change the background opacity by targeting `yarl__container` css class.

```css
.yarl__container {
    background-color: rgba(0 0 0 / 80%);
}
```

Does this address your case?

**Comment by d4mr** [comment]
> You can change the background opacity by targeting `yarl__container` css class.
> 
> ```css
> .yarl__container {
>     background-color: rgba(0 0 0 / 80%);
> }
> ```
> 
> Does this address your case?

Yes this is what I am currently using as well. However since these classes seem to be undocumented, I thought there were no guarantees for the class name staying the same. and a future version breaking my opacity implementation.

If these classes are guaranteed to stay the same, then this solves my problem!

PS: Great work on the library! This seems to be the only simple and minimal updated package for the job. Thanks for building this :)

**Comment by igordanchenko** [comment]
I hear your concern, but here is my dilemma. Given the amount of CSS in this library, I decided not to use CSS-in-JS (or at least keep it to a bare minimum) in favor of pure CSS styling. The only exception to this rule is the properties the JS code needs to be aware of (e.g., fade animation duration or padding around slides). I'm very reluctant to add any additional style-related customization options as React component props because there are just way too many things to customize, and CSS is a perfect tool for the job. 

And you are absolutely correct that CSS classes are technically undocumented. I'll obviously do my best to release any significant CSS-related changes through a major version bump, but there is always a chance some refactoring may break CSS customizations for some users in the future.

Do you have any suggestions on how to solve this problem?

**Comment by igordanchenko** [comment]
I'm reopening this feature request since I feel that I need to implement a more robust solution here. @d4mr, I'll share a draft with you when it's ready.

**Comment by igordanchenko** [comment]
@d4mr, I decided to proceed with the following customization approach. 

- I'll define a set of customization slots ("root", "container", "button", "icon", etc.) that library consumers would typically want to style / customize
- each slot will allow styling from the JS code via CSS-in-JS styles
- each slot will be tagged with a stable CSS class name ("yarl__root", "yarl__container", etc.), these classes will be documented and considered a part of the public API
- each slot will allow attaching custom classes (for example, if you want to use Tailwind CSS utility classes)

So in total, there will be 3 customization options.

1) Directly in the JS code:

```jsx
<Lightbox
  styles={{ container: { backgroundColor: "rgb(0 0 0 / 70%)" } }}
/>
```

2) CSS (target lightbox slots):

```css
.yarl__container {
  background-color: rgb(0 0 0 / 70%);
}
```


3) CSS (attach custom classes):

```jsx
<Lightbox
  classes={{ container: "bg-black/70" }}
/>
```

Please let me know if you have any feedback.
