### ISSUE TITLE
PDF viewer support

### ISSUE THREAD

**Issue by chetra-seng** [igordanchenko/yet-another-react-lightbox#60]
### Is your feature request related to a problem? Please describe.

I've been working on a form submission with file attachments, which includes images and pdf files. I've tried other libraries to make it possible to view both types using the same lightbox. No luck so far. Tried this library and love it due to ease of use. I was wondering if you can support for pdf files? 

### Describe the solution you'd like

Would be nice if I could add pdf file to slides along side images.
```
const slides = [
  { src: "/image1.jpg" },
  { src: "/ file1.pdf" },
  { src: "/file2.pdf" },
  // ...
];
```

**Comment by igordanchenko** [comment]
Sorry, but I have no plans for adding support for PDF files due to several reasons: a) I don't believe there is a single "gold standard" way of embedding a PDF file into a web page (and supporting all of them would be an over-kill); b) PDF embeds obscure touch / click events leading to poor swipe gesture / click-and-drag UX. I'll be happy to revisit this decision if you can suggest a way to address the above concerns.

However, you can always render your own [custom slides](https://yet-another-react-lightbox.com/examples/custom-slides) with a custom [render](https://yet-another-react-lightbox.com/documentation#Render) function.
