### ISSUE TITLE
cant test library images showing using jest

### ISSUE THREAD

**Issue by OriAmir** [igordanchenko/yet-another-react-lightbox#66]
### Describe the bug

hi, I work with `jest` and `ESM` and I got an error when I tried to check the library labels showing as expected.

for example, this is my simple test:

   ```
 render(
      <ResponsiveGallery
        useLightBox
        images={[
          {
            src: "src1",
            title: "src 1 title",
            description: "src 1 descriotion",
          },
        ]}
      />
    );
    const domImages: HtmlImages = screen.getAllByRole("img");
    fireEvent.click(domImages[0]);

    await screen.findByText("src 1 title");
    await screen.findByText("src 1 description");
```

and I got an error about the library:
Details:
```
Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
 • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/configuration
For information about custom transformations, see:
https://jestjs.io/docs/code-transformation

Details:

/Users/oriamir/Documents/Gallery/React-Responsive-Gallery/node_modules/yet-another-react-lightbox/dist/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { Lightbox } from "./Lightbox.js";
                                                                                  ^^^^^^

SyntaxError: Cannot use import statement outside a moduleJest
                                                                                  ^^^^^^
```

### Expected behavior

test will pass.

### How to reproduce

1. render the library in React project build with ESM
2. try to test your component with jest.
3. see the error

**Comment by igordanchenko** [comment]
Based on the details you provided above, it looks like there is an issue with your jest/ESM configuration. I'm pretty sure you'd see the same error with any other 3rd-party ESM-only library, so I do not see how this is a YARL issue. I'm going to close this ticket since troubleshooting very specific jest configuration issues is outside the scope of this library maintenance.

**Comment by OriAmir** [comment]
@igordanchenko thanks for the response, actually not sure it's on my side since all the other tests I have are passing other than the ones that I render the library.
I see you commented here https://github.com/igordanchenko/yet-another-react-lightbox/issues/7 to ignore the library but I'm not sure why?

thanks

**Comment by igordanchenko** [comment]
> actually not sure it's on my side since all the other tests I have are passing other than the ones that I render the library.

I'm pretty sure that's because YARL is currently the only ESM-only library among your dependencies. I bet you'd see the same Jest error if you were to use any other ESM-only library. For example, you can try including [micromark](https://www.npmjs.com/package/micromark) as a quick test.

```jsx
import {micromark} from 'micromark'

// ...

<>{micromark('## Hello, *world*!')}</>
```

As I understand it, Jest does not handle ES6 `import` / `export` statements. And since Jest by default excludes `node_modules` from all transformations, it fails to load 3rd-party ESM-only packages. One way to overcome this Jest limitation is to instruct Jest to enable transformations on specific dependencies.

```js
// jest.config.js

const esModules = ["yet-another-react-lightbox"];

module.exports = {
  testEnvironment: "jsdom",
  transformIgnorePatterns: [`node_modules/(?!${esModules.join("|")})`],
};
```

This workaround worked for me in a project using `jest` and `ts-node`. I hope this works in your case as well.

**Comment by trevor-james-nangosha** [comment]
Hello.
I could really use some help because I am currently facing the same issue and I can't seem to find a way forward. I have tried all the options above, but they just won't work for me!

Details:
```
jest - "^29.7.0"
YARL - "3.11.3"
```

Here's my jest config:
``` js
/** @type {import('jest').Config} */

const config = {
  verbose: true,
  transform: {
      "^.+\\.(js|jsx)$": "babel-jest",
  },
  setupFilesAfterEnv: ["<rootDir>/setup-jest.js"],
    transformIgnorePatterns: ["<rootDir>/node_modules/(?!yet-another-react-lightbox)"],
    testEnvironment: "jsdom",
};
module.exports = config;
```

And this is my babel config:
```
{
  "plugins": ["@emotion/babel-plugin"],
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

I have also tried the examples given in #148 but they won't work for me too!
Thanks!
@igordanchenko

**Comment by igordanchenko** [comment]
@trevor-james-nangosha have you tried using the default `babel-jest` transform pattern listed in the [Jest documentation](https://jestjs.io/docs/code-transformation#defaults) or completely removing the `transform` config option? 

```json
"transform": {
  "\\.[jt]sx?$": "babel-jest"
},
```

**Comment by trevor-james-nangosha** [comment]
Let me try that and get back to you!

**Comment by igordanchenko** [comment]
Please feel free to share a minimal repro on StackBlitz or CodeSandbox.
